chainNormal:
  chainTypeA: 0001
  chainTypeB: 0010
  chainTypeC: 0011
  chainTypeD: 0100
  chainTypeE: 0101
  chainTypeF: 0110
  chainTypeG: 0111
  chainTypeH: 1000
  chainTypeI: 1001
  chainTypeJ: 1011
  chainTypeK: 1100
  chainTypeL: 1101
  chainTypeM: 1110

chainSpecial:
  chainSpecialOne: 0000
  chainSpecialTwo: 0001